name: Test Pull Request
on:
  pull_request:

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2.4.0

      - name: Test Chrome image
        uses: docker/build-push-action@v2.9.0
        with:
          target: test-chrome
          push: false

      - name: Test Chrome + Python image
        uses: docker/build-push-action@v2.9.0
        with:
          target: test-python
          push: false

      - name: Test Chrome + Jupyter image
        uses: docker/build-push-action@v2.9.0
        with:
          target: test-jupyter
          push: false

      - name: Test devcontainer image
        uses: docker/build-push-action@v2.9.0
        with:
          target: test-vscode
          push: false

      - name: Test devcontainer + Python image
        uses: docker/build-push-action@v2.9.0
        with:
          target: test-python-vscode
          push: false

      - name: Test devcontainer + Jupyter image
        uses: docker/build-push-action@v2.9.0
        with:
          target: test-jupyter-vscode
          push: false
